import type { Business, BusinessTheme, WebsiteSection } from "./types";

export const defaultBusiness: Business = {
  name: "",
  slug: "",
  type: "Food business",
  tagline: "",
  description: "",
  story: "",
  email: "",
  phone: "",
  whatsapp: "",
  city: "",
  address: "",
  serviceAreas: [],
  logo: "",
  published: false,
  foundedYear: "",
  teamSize: "",
  languages: [],
  certifications: [],
  awards: [],
  minimumGuests: "",
  bookingNotice: "",
  cancellationPolicy: "",
  depositPolicy: "",
  travelPolicy: "",
  openingHours: [],
  social: {
    instagram: "",
    facebook: "",
    tiktok: "",
    pinterest: "",
    youtube: "",
  },
  mapUrl: "",
};

export const defaultTheme: BusinessTheme = {
  template: "editorial",
  primary: "#233a31",
  accent: "#c79d59",
  surface: "#fdfcf8",
  headingFont: "Cormorant Garamond",
  bodyFont: "Inter",
  headingScale: "balanced",
  buttonShape: "soft",
  imageCorners: "soft",
  sectionSpacing: "comfortable",
  navigation: "minimal",
  heroImage: "",
  heroLayout: "overlay",
  heroHeight: "grand",
  heroOverlay: 62,
  headerStyle: "transparent",
  showAnnouncement: false,
  announcementText: "",
  showMenuPrices: true,
  showDietaryLabels: true,
  showAllergens: true,
  showSocialLinks: true,
  showOpeningHours: true,
  aboutImage: "",
  detailImage: "",
  galleryLayout: "editorial",
  menuLayout: "editorial",
  serviceLayout: "cards",
  menuItemLimit: 6,
  galleryLimit: 7,
};

export const defaultSections: WebsiteSection[] = [
  { id: "hero", label: "Hero", eyebrow: "Welcome", title: "Gather beautifully. Dine memorably.", body: "Tell visitors what makes your food unforgettable.", ctaLabel: "Plan your event", secondaryCtaLabel: "Explore our menus", visible: true },
  { id: "stats", label: "Highlights", eyebrow: "By the numbers", title: "A track record worth sharing", body: "The experience behind everything you serve.", visible: true },
  { id: "about", label: "About", eyebrow: "Our story", title: "Hospitality, thoughtfully prepared", body: "Share the story and values behind your business.", ctaLabel: "Meet our team", visible: true },
  { id: "services", label: "Services", eyebrow: "What we do", title: "Made for your kind of gathering", body: "Describe the events and services you offer.", visible: true },
  { id: "process", label: "How it works", eyebrow: "Planning with us", title: "From first call to final course", body: "Walk guests through what happens after they reach out.", visible: true },
  { id: "menus", label: "Featured menus", eyebrow: "From the kitchen", title: "Menus your guests will remember", body: "Highlight a few signature dishes or packages.", ctaLabel: "View the full menu", visible: true },
  { id: "gallery", label: "Gallery", eyebrow: "Gatherings", title: "A table worth remembering", body: "Show off photos of past events and dishes.", ctaLabel: "Explore our work", visible: true },
  { id: "team", label: "Team", eyebrow: "The people", title: "The team behind your table", body: "Introduce the people who make your events happen.", visible: true },
  { id: "testimonials", label: "Testimonials", eyebrow: "Kind words", title: "Notes from our tables", body: "Share feedback from hosts who trusted you with their gathering.", visible: true },
  { id: "faq", label: "Frequently asked", eyebrow: "Planning details", title: "A few things hosts often ask", body: "Answer the questions guests ask most before booking.", visible: true },
  { id: "quote", label: "Quote request", eyebrow: "Begin a conversation", title: "Tell us about your event", body: "Share a few details and our team will follow up soon.", ctaLabel: "Send event request", visible: true },
  { id: "contact", label: "Contact", eyebrow: "Get in touch", title: "Let's plan something memorable", body: "Let visitors know where and how to reach you.", visible: true },
  { id: "footer", label: "Footer", eyebrow: "", title: "", body: "", visible: true },
];
