import type { AppState } from "./types";

const food = {
  hero: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1800&q=85",
  salmon: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
  mezze: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
  chicken: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80",
  beef: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
  cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
  salad: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80",
  bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
  dinner: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80",
  table: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
  wedding: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80",
  chef: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1200&q=80",
};

export const initialData: AppState = {
  business: {
    name: "Olive & Ember Catering",
    slug: "olive-and-ember",
    type: "Kosher catering",
    tagline: "Gather beautifully. Dine memorably.",
    description:
      "Olive & Ember creates thoughtfully prepared menus for weddings, private dinners, corporate events, and Shabbat gatherings. Every menu combines generous hospitality, refined presentation, and flavors inspired by Mediterranean cooking.",
    email: "hello@oliveandember.com",
    phone: "(305) 555-0148",
    whatsapp: "+1 305 555 0148",
    city: "Miami Beach, Florida",
    address: "Miami Beach, FL",
    serviceAreas: ["Miami Beach", "Aventura", "Coral Gables", "Fort Lauderdale"],
    published: true,
  },
  theme: {
    template: "editorial",
    primary: "#233a31",
    accent: "#c79d59",
    headingFont: "Cormorant",
    bodyFont: "Inter",
    buttonShape: "soft",
    imageCorners: "soft",
    sectionSpacing: "comfortable",
    navigation: "minimal",
    heroImage: food.hero,
  },
  sections: [
    { id: "hero", label: "Hero", title: "Gather beautifully. Dine memorably.", body: "Elegant kosher catering for unforgettable gatherings in Miami.", visible: true },
    { id: "about", label: "About", title: "Hospitality, thoughtfully prepared", body: "Mediterranean-inspired menus, refined presentation, and warm service for life's most meaningful tables.", visible: true },
    { id: "services", label: "Services", title: "Made for your kind of gathering", body: "From intimate Shabbat dinners to celebrations for hundreds, every detail is tailored to your event.", visible: true },
    { id: "menus", label: "Featured menus", title: "Menus your guests will remember", body: "Seasonal ingredients, generous portions, and thoughtful options for every table.", visible: true },
    { id: "gallery", label: "Gallery", title: "Recent gatherings", body: "A glimpse of the tables, flavors, and moments we help bring to life.", visible: true },
    { id: "testimonials", label: "Testimonials", title: "Notes from our tables", body: "Kind words from hosts who trusted us with their gathering.", visible: true },
    { id: "quote", label: "Quote request", title: "Tell us about your event", body: "Share a few details and our team will follow up within one business day.", visible: true },
    { id: "contact", label: "Contact", title: "Let’s plan something memorable", body: "Serving Miami-Dade, Broward, and select South Florida destinations.", visible: true },
    { id: "footer", label: "Footer", title: "Olive & Ember Catering", body: "Gather beautifully. Dine memorably.", visible: true },
  ],
  categories: [
    { id: "appetizers", name: "Appetizers" },
    { id: "mains", name: "Main courses" },
    { id: "sides", name: "Side dishes" },
    { id: "desserts", name: "Desserts" },
    { id: "packages", name: "Event packages" },
    { id: "shabbat", name: "Shabbat menus" },
  ],
  menuItems: [
    { id: "m1", name: "Mediterranean mezze table", description: "Hummus, smoky eggplant, matbucha, olives, pickles, and warm pita.", price: "$24", pricingUnit: "Per person", image: food.mezze, categoryId: "appetizers", dietary: ["Kosher", "Pareve", "Vegan"], allergens: ["Sesame", "Gluten"], minimumOrder: "20 guests", available: true, views: 184 },
    { id: "m2", name: "Herb-roasted salmon", description: "Atlantic salmon, preserved lemon, herbs, and market vegetables.", price: "$32", pricingUnit: "Per person", image: food.salmon, categoryId: "mains", dietary: ["Kosher", "Pareve", "Gluten-free"], allergens: ["Fish"], minimumOrder: "12 guests", available: true, views: 263 },
    { id: "m3", name: "Date-glazed chicken", description: "Slow-roasted chicken with medjool dates, shallots, and thyme.", price: "$28", pricingUnit: "Per person", image: food.chicken, categoryId: "mains", dietary: ["Kosher", "Meat", "Gluten-free"], allergens: [], minimumOrder: "12 guests", available: true, views: 216 },
    { id: "m4", name: "Braised short rib", description: "Red wine braised beef with silan jus and root vegetables.", price: "$38", pricingUnit: "Per person", image: food.beef, categoryId: "mains", dietary: ["Kosher", "Meat", "Gluten-free"], allergens: [], minimumOrder: "20 guests", available: true, views: 198 },
    { id: "m5", name: "Charred market vegetables", description: "Seasonal vegetables, herb oil, toasted seeds, and sea salt.", price: "$72", pricingUnit: "Per tray", image: food.salad, categoryId: "sides", dietary: ["Kosher", "Pareve", "Vegan", "Gluten-free"], allergens: ["Seeds"], minimumOrder: "1 tray", available: true, views: 92 },
    { id: "m6", name: "Honey & pistachio cake", description: "Orange blossom sponge, honey cream, and roasted pistachios.", price: "$12", pricingUnit: "Per item", image: food.cake, categoryId: "desserts", dietary: ["Kosher", "Dairy", "Vegetarian"], allergens: ["Dairy", "Eggs", "Nuts"], minimumOrder: "12 servings", available: true, views: 147 },
    { id: "m7", name: "Friday night table", description: "Challah, five salads, soup, two mains, three sides, and dessert.", price: "$64", pricingUnit: "Per person", image: food.bread, categoryId: "shabbat", dietary: ["Kosher", "Meat"], allergens: ["Gluten", "Eggs"], minimumOrder: "10 guests", available: true, views: 231 },
    { id: "m8", name: "Signature celebration", description: "Cocktail hour, plated dinner, dessert table, and full event service.", price: "$145", pricingUnit: "Starting at", image: food.dinner, categoryId: "packages", dietary: ["Kosher"], allergens: [], minimumOrder: "50 guests", available: true, views: 174 },
  ],
  gallery: [
    { id: "g1", url: food.table, caption: "Mediterranean wedding table", category: "Weddings", featured: true },
    { id: "g2", url: food.chef, caption: "Chef-prepared private dinner", category: "Private dinners", featured: false },
    { id: "g3", url: food.wedding, caption: "An evening celebration", category: "Weddings", featured: false },
    { id: "g4", url: food.hero, caption: "Seasonal event menu", category: "Food presentation", featured: false },
    { id: "g5", url: food.dinner, caption: "Corporate lunch spread", category: "Corporate events", featured: false },
    { id: "g6", url: food.bread, caption: "A Friday night table", category: "Shabbat", featured: false },
  ],
  leads: [
    { id: "l1", customerName: "Rachel Levin", email: "rachel@example.com", phone: "(305) 555-0182", eventDate: "2026-09-14", eventLocation: "Vizcaya Museum", eventType: "Wedding", guestCount: 120, budget: "$15,000–$20,000", preferredMenu: "Signature celebration", dietaryRequirements: "Kosher; 4 vegan meals", details: "Outdoor cocktail hour followed by a plated dinner.", preferredContact: "Email", receivedAt: "2026-07-24", status: "New", notes: [] },
    { id: "l2", customerName: "Daniel Cohen", email: "daniel@example.com", phone: "(786) 555-0129", eventDate: "2026-08-08", eventLocation: "Aventura", eventType: "Shabbat dinner", guestCount: 28, budget: "$2,500–$4,000", preferredMenu: "Friday night table", dietaryRequirements: "Nut-free table", details: "Family-style dinner at home.", preferredContact: "WhatsApp", receivedAt: "2026-07-20", status: "Contacted", notes: [{ id: "n1", text: "Sent sample Shabbat menu.", createdAt: "2026-07-21" }] },
    { id: "l3", customerName: "Maya Torres", email: "maya@example.com", phone: "(954) 555-0104", eventDate: "2026-10-02", eventLocation: "Brickell", eventType: "Corporate event", guestCount: 75, budget: "$6,000–$8,000", preferredMenu: "Mediterranean", dietaryRequirements: "Vegetarian options", details: "Client dinner with passed appetizers.", preferredContact: "Phone", receivedAt: "2026-07-16", status: "Quote sent", notes: [] },
  ],
  subscription: { plan: "Business", price: 249, status: "Trial" },
  notifications: { emailLeads: true, whatsapp: false, weeklySummary: true },
  onboarded: true,
};
