import type { AppState } from "./types";

const food = {
  hero: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=1800&q=85",
  salmon: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80",
  mezze: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
  chicken: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=900&q=80",
  beef: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
  cake: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
  salad: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=900&q=80",
  bread: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
  dinner: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80",
  table: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80",
  wedding: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80",
  chef: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1200&q=80",
  corporate: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
  shabbat: "https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=1200&q=80",
  pastry: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=900&q=80",
  cocktail: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=1200&q=80",
  sousChef: "https://images.unsplash.com/photo-1583394293214-28a5b42f7f11?auto=format&fit=crop&w=900&q=80",
  host: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
  pastryChef: "https://images.unsplash.com/photo-1607631568010-a87245c0dbd6?auto=format&fit=crop&w=900&q=80",
};

export const initialData: AppState = {
  business: {
    name: "Olive & Ember Catering",
    slug: "olive-and-ember",
    type: "Kosher catering",
    tagline: "Gather beautifully. Dine memorably.",
    description:
      "Olive & Ember creates thoughtfully prepared menus for weddings, private dinners, corporate events, and Shabbat gatherings. Every menu combines generous hospitality, refined presentation, and flavors inspired by Mediterranean cooking.",
    story:
      "We began in 2014 with a single Friday-night table and a belief that the food at a celebration should feel as personal as the people around it. Today our kitchen serves South Florida with seasonal, kosher-certified menus, but the way we work has not changed: we cook the way we would for our own family, we plan every detail in advance, and we treat your guests as ours.",
    email: "hello@oliveandember.com",
    phone: "(305) 555-0148",
    whatsapp: "+1 305 555 0148",
    city: "Miami Beach, Florida",
    address: "1420 Alton Road, Miami Beach, FL 33139",
    serviceAreas: ["Miami Beach", "Aventura", "Coral Gables", "Fort Lauderdale", "Bal Harbour", "Sunny Isles"],
    published: true,
    foundedYear: "2014",
    teamSize: "18 chefs and service staff",
    languages: ["English", "Hebrew", "Spanish"],
    certifications: ["Kosher certified (ORB)", "ServSafe certified kitchen", "Florida licensed caterer"],
    awards: ["Best Kosher Caterer, Miami Dining Awards 2024", "Featured in South Florida Weddings"],
    minimumGuests: "10 guests for drop-off, 30 for full service",
    bookingNotice: "Two weeks for intimate dinners, three months for weddings",
    cancellationPolicy: "Full refund up to 30 days before your event; 50% up to 14 days.",
    depositPolicy: "A 25% deposit confirms your date. The balance is due five days before the event.",
    travelPolicy: "Complimentary within 25 miles of Miami Beach. Travel beyond is quoted per event.",
    openingHours: [
      { id: "h1", days: "Sunday – Thursday", hours: "9:00 – 18:00" },
      { id: "h2", days: "Friday", hours: "8:00 – 14:00" },
      { id: "h3", days: "Saturday", hours: "Closed for Shabbat" },
    ],
    social: {
      instagram: "https://instagram.com/oliveandember",
      facebook: "https://facebook.com/oliveandember",
      tiktok: "",
      pinterest: "https://pinterest.com/oliveandember",
      youtube: "",
    },
    mapUrl: "https://maps.google.com/?q=1420+Alton+Road+Miami+Beach",
  },
  theme: {
    template: "editorial",
    primary: "#233a31",
    accent: "#c79d59",
    surface: "#fdfcf8",
    headingFont: "Cormorant Garamond",
    bodyFont: "Inter",
    headingScale: "balanced",
    buttonShape: "soft",
    imageCorners: "soft",
    sectionSpacing: "comfortable",
    navigation: "minimal",
    heroImage: food.hero,
    heroLayout: "overlay",
    heroHeight: "grand",
    heroOverlay: 62,
    headerStyle: "transparent",
    showAnnouncement: true,
    announcementText: "Now booking fall celebrations across South Florida",
    showMenuPrices: true,
    showDietaryLabels: true,
    showAllergens: true,
    showSocialLinks: true,
    showOpeningHours: true,
    aboutImage: food.chef,
    detailImage: food.table,
    galleryLayout: "editorial",
    menuLayout: "editorial",
    serviceLayout: "cards",
    menuItemLimit: 6,
    galleryLimit: 7,
  },
  sections: [
    { id: "hero", label: "Hero", eyebrow: "Kosher catering · Miami", title: "Gather beautifully. Dine memorably.", body: "Elegant kosher catering for unforgettable gatherings in Miami.", ctaLabel: "Plan your event", secondaryCtaLabel: "Explore our menus", visible: true },
    { id: "stats", label: "Highlights", eyebrow: "By the numbers", title: "A decade of beautiful tables", body: "The experience behind every event we cater.", visible: true },
    { id: "about", label: "About", eyebrow: "Our table", title: "Hospitality, thoughtfully prepared", body: "Mediterranean-inspired menus, refined presentation, and warm service for life's most meaningful tables.", ctaLabel: "Meet Olive & Ember", visible: true },
    { id: "services", label: "Services", eyebrow: "What we do", title: "Made for your kind of gathering", body: "From intimate Shabbat dinners to celebrations for hundreds, every detail is tailored to your event.", visible: true },
    { id: "process", label: "How it works", eyebrow: "Planning with us", title: "From first call to final course", body: "A calm, well-mapped process so you always know what happens next.", visible: true },
    { id: "menus", label: "Featured menus", eyebrow: "From the kitchen", title: "Menus your guests will remember", body: "Seasonal ingredients, generous portions, and thoughtful options for every table.", ctaLabel: "View the full menu", visible: true },
    { id: "gallery", label: "Gallery", eyebrow: "Gatherings", title: "A table worth remembering", body: "A glimpse of the tables, flavors, and moments we help bring to life.", ctaLabel: "Explore our work", visible: true },
    { id: "team", label: "Team", eyebrow: "The people", title: "The team behind your table", body: "A small kitchen brigade and service team who will know your event by heart.", visible: true },
    { id: "testimonials", label: "Testimonials", eyebrow: "Kind words", title: "Notes from our tables", body: "Kind words from hosts who trusted us with their gathering.", visible: true },
    { id: "faq", label: "Frequently asked", eyebrow: "Planning details", title: "A few things hosts often ask", body: "Helpful answers before we begin planning your gathering.", visible: true },
    { id: "quote", label: "Quote request", eyebrow: "Begin a conversation", title: "Tell us about your event", body: "Share a few details and our team will follow up within one business day.", ctaLabel: "Send event request", visible: true },
    { id: "contact", label: "Contact", eyebrow: "South Florida", title: "Let’s plan something memorable", body: "Serving Miami-Dade, Broward, and select South Florida destinations.", visible: true },
    { id: "footer", label: "Footer", eyebrow: "Olive & Ember", title: "Olive & Ember Catering", body: "Gather beautifully. Dine memorably.", visible: true },
  ],
  services: [
    { id: "s1", title: "Weddings & celebrations", description: "Elegant menus, seamless service, and a table designed around the way you want to celebrate.", image: food.wedding, priceFrom: "$145 per guest", capacity: "40–350 guests", highlights: ["Tasting for two included", "Cocktail hour & plated dinner", "Full service staff"] },
    { id: "s2", title: "Private chef dinners", description: "Restaurant-level dining brought into your home, from the first pour to the final course.", image: food.chef, priceFrom: "$95 per guest", capacity: "6–24 guests", highlights: ["Menu designed with you", "Chef cooks on site", "Kitchen left spotless"] },
    { id: "s3", title: "Corporate gatherings", description: "Thoughtful food and polished hospitality for teams, launches, and important clients.", image: food.corporate, priceFrom: "$38 per guest", capacity: "15–500 guests", highlights: ["Breakfast to dinner", "Invoicing & PO friendly", "Dietary labelling included"] },
    { id: "s4", title: "Shabbat & holidays", description: "Generous, ready-to-serve menus that make meaningful tables feel effortless.", image: food.shabbat, priceFrom: "$64 per guest", capacity: "10–120 guests", highlights: ["Delivered warm & ready", "Reheating instructions", "Kosher certified"] },
  ],
  testimonials: [
    { id: "t1", quote: "From the first tasting to the final plate, every detail felt generous, beautiful, and completely us.", author: "Rachel & Levi", context: "Wedding · Miami Beach", rating: 5, eventDate: "March 2026" },
    { id: "t2", quote: "Our guests are still talking about the food. The team made a 90-person dinner feel wonderfully intimate.", author: "Maya Torres", context: "Corporate dinner · Brickell", rating: 5, eventDate: "January 2026" },
    { id: "t3", quote: "The Shabbat table arrived ready to welcome everyone. It was warm, abundant, and genuinely special.", author: "Daniel Cohen", context: "Private gathering · Aventura", rating: 5, eventDate: "November 2025" },
  ],
  faqs: [
    { id: "f1", question: "How far in advance should we book?", answer: "For weddings and larger events, we recommend reaching out three to six months ahead. Intimate dinners and Shabbat menus can often be arranged with two to four weeks’ notice." },
    { id: "f2", question: "Can you accommodate dietary requirements?", answer: "Yes. We regularly plan vegetarian, vegan, gluten-free, nut-aware, and other tailored menus while maintaining kosher standards." },
    { id: "f3", question: "Do you provide staffing and rentals?", answer: "Full-service events can include chefs, service staff, tabletop coordination, and trusted rental partners. We’ll shape the service around your venue and guest experience." },
    { id: "f4", question: "Can we customize a menu?", answer: "Absolutely. Our sample menus are a starting point. Every event proposal is tailored to the season, your guests, and the way you want to host." },
    { id: "f5", question: "What does a deposit look like?", answer: "A 25% deposit confirms your date, with the balance due five days before the event. Cancellations are fully refundable up to 30 days ahead." },
    { id: "f6", question: "Do you travel outside Miami Beach?", answer: "Travel is complimentary within 25 miles. Destination events across South Florida and the Keys are quoted per event." },
  ],
  stats: [
    { id: "n1", value: "12+", label: "Years around beautiful tables" },
    { id: "n2", value: "640", label: "Events catered since 2014" },
    { id: "n3", value: "18", label: "Chefs and service staff" },
    { id: "n4", value: "4.9", label: "Average host rating" },
  ],
  processSteps: [
    { id: "p1", title: "Share your event", description: "Tell us the date, guest count, venue, and the feeling you want the table to have.", duration: "5 minutes" },
    { id: "p2", title: "Receive a tailored proposal", description: "We design a menu and service plan around your guests, budget, and dietary needs.", duration: "Within 2 days" },
    { id: "p3", title: "Taste and refine", description: "Sit down with our chef, taste the menu, and adjust every detail until it feels right.", duration: "2–4 weeks before" },
    { id: "p4", title: "We take it from here", description: "Our team arrives early, sets the table, serves your guests, and leaves the space spotless.", duration: "Event day" },
  ],
  team: [
    { id: "tm1", name: "Ella Bar-On", role: "Executive chef & founder", bio: "Trained in Tel Aviv and Provence, Ella builds every menu around the season and the story of the table.", image: food.chef },
    { id: "tm2", name: "Yosef Marcu", role: "Head of events", bio: "Yosef maps the timeline, staffing, and logistics so the evening feels effortless from the first guest.", image: food.sousChef },
    { id: "tm3", name: "Noa Feldman", role: "Pastry chef", bio: "Noa's desserts pair Mediterranean flavors with the kind of finish guests photograph before tasting.", image: food.pastryChef },
  ],
  categories: [
    { id: "appetizers", name: "Appetizers", description: "Passed bites, mezze, and grazing tables to open the evening." },
    { id: "mains", name: "Main courses", description: "Plated or family-style centrepieces built around the season." },
    { id: "sides", name: "Side dishes", description: "Vegetables, grains, and salads made to share." },
    { id: "desserts", name: "Desserts", description: "Cakes, pastries, and sweet tables." },
    { id: "packages", name: "Event packages", description: "Complete service packages from cocktail hour to last course." },
    { id: "shabbat", name: "Shabbat menus", description: "Ready-to-serve Friday night and Shabbat lunch tables." },
  ],
  menuItems: [
    { id: "m1", name: "Mediterranean mezze table", description: "Hummus, smoky eggplant, matbucha, olives, pickles, and warm pita.", price: "$24", pricingUnit: "Per person", image: food.mezze, categoryId: "appetizers", dietary: ["Kosher", "Pareve", "Vegan"], allergens: ["Sesame", "Gluten"], ingredients: "Chickpeas, tahini, roasted eggplant, tomato, garlic, olive oil, house pita", servingSize: "6–8 pieces per guest", preparation: "Assembled on site on wooden boards", leadTime: "72 hours", minimumOrder: "20 guests", seasonal: "Year round", featured: true, available: true, views: 184 },
    { id: "m2", name: "Herb-roasted salmon", description: "Atlantic salmon, preserved lemon, herbs, and market vegetables.", price: "$32", pricingUnit: "Per person", image: food.salmon, categoryId: "mains", dietary: ["Kosher", "Pareve", "Gluten-free"], allergens: ["Fish"], ingredients: "Atlantic salmon, preserved lemon, parsley, dill, seasonal vegetables", servingSize: "220g portion", preparation: "Roasted on site, served warm", leadTime: "72 hours", minimumOrder: "12 guests", seasonal: "Year round", featured: true, available: true, views: 263 },
    { id: "m3", name: "Date-glazed chicken", description: "Slow-roasted chicken with medjool dates, shallots, and thyme.", price: "$28", pricingUnit: "Per person", image: food.chicken, categoryId: "mains", dietary: ["Kosher", "Meat", "Gluten-free"], allergens: [], ingredients: "Free-range chicken, medjool dates, shallot, thyme, silan", servingSize: "Half chicken per guest", preparation: "Slow roasted, finished on site", leadTime: "72 hours", minimumOrder: "12 guests", seasonal: "Year round", featured: false, available: true, views: 216 },
    { id: "m4", name: "Braised short rib", description: "Red wine braised beef with silan jus and root vegetables.", price: "$38", pricingUnit: "Per person", image: food.beef, categoryId: "mains", dietary: ["Kosher", "Meat", "Gluten-free"], allergens: [], ingredients: "Beef short rib, red wine, silan, carrot, celery root, thyme", servingSize: "250g portion", preparation: "Braised 6 hours, plated to order", leadTime: "5 days", minimumOrder: "20 guests", seasonal: "October – April", featured: true, available: true, views: 198 },
    { id: "m5", name: "Charred market vegetables", description: "Seasonal vegetables, herb oil, toasted seeds, and sea salt.", price: "$72", pricingUnit: "Per tray", image: food.salad, categoryId: "sides", dietary: ["Kosher", "Pareve", "Vegan", "Gluten-free"], allergens: ["Seeds"], ingredients: "Market vegetables, herb oil, pumpkin and sunflower seeds, sea salt", servingSize: "Serves 10–12", preparation: "Charred over open flame", leadTime: "48 hours", minimumOrder: "1 tray", seasonal: "Changes weekly", featured: false, available: true, views: 92 },
    { id: "m6", name: "Honey & pistachio cake", description: "Orange blossom sponge, honey cream, and roasted pistachios.", price: "$12", pricingUnit: "Per item", image: food.cake, categoryId: "desserts", dietary: ["Kosher", "Dairy", "Vegetarian"], allergens: ["Dairy", "Eggs", "Nuts"], ingredients: "Orange blossom sponge, honey cream, roasted pistachio, citrus zest", servingSize: "One slice", preparation: "Baked the morning of your event", leadTime: "72 hours", minimumOrder: "12 servings", seasonal: "Year round", featured: false, available: true, views: 147 },
    { id: "m7", name: "Friday night table", description: "Challah, five salads, soup, two mains, three sides, and dessert.", price: "$64", pricingUnit: "Per person", image: food.bread, categoryId: "shabbat", dietary: ["Kosher", "Meat"], allergens: ["Gluten", "Eggs"], ingredients: "House challah, seasonal salads, soup, two mains, sides, dessert", servingSize: "Full Friday night table", preparation: "Delivered warm with reheating instructions", leadTime: "Order by Wednesday", minimumOrder: "10 guests", seasonal: "Every week", featured: true, available: true, views: 231 },
    { id: "m8", name: "Signature celebration", description: "Cocktail hour, plated dinner, dessert table, and full event service.", price: "$145", pricingUnit: "Starting at", image: food.dinner, categoryId: "packages", dietary: ["Kosher"], allergens: [], ingredients: "Six passed canapés, plated three-course dinner, dessert table", servingSize: "Full evening service", preparation: "Full brigade and service staff on site", leadTime: "3 months", minimumOrder: "50 guests", seasonal: "Year round", featured: true, available: true, views: 174 },
    { id: "m9", name: "Sunrise pastry table", description: "Butter croissants, seasonal danishes, granola jars, and fresh juice.", price: "$21", pricingUnit: "Per person", image: food.pastry, categoryId: "appetizers", dietary: ["Kosher", "Dairy", "Vegetarian"], allergens: ["Gluten", "Dairy", "Eggs"], ingredients: "Butter pastry, seasonal fruit, house granola, cold-pressed juice", servingSize: "3 pieces per guest", preparation: "Baked at dawn and delivered", leadTime: "48 hours", minimumOrder: "15 guests", seasonal: "Year round", featured: false, available: true, views: 88 },
    { id: "m10", name: "Cocktail hour canapés", description: "Eight passed bites, from tuna crudo to zaatar arancini.", price: "$34", pricingUnit: "Per person", image: food.cocktail, categoryId: "packages", dietary: ["Kosher", "Pareve"], allergens: ["Fish", "Gluten"], ingredients: "Seasonal seafood, vegetables, herbs, house doughs", servingSize: "8 pieces per guest", preparation: "Passed by service staff for 60 minutes", leadTime: "2 weeks", minimumOrder: "30 guests", seasonal: "Year round", featured: false, available: true, views: 126 },
  ],
  gallery: [
    { id: "g1", url: food.table, caption: "Mediterranean wedding table", category: "Weddings", eventType: "Wedding", guestCount: "180 guests", location: "Vizcaya, Miami", featured: true },
    { id: "g2", url: food.chef, caption: "Chef-prepared private dinner", category: "Private dinners", eventType: "Private chef dinner", guestCount: "12 guests", location: "Bal Harbour", featured: false },
    { id: "g3", url: food.wedding, caption: "An evening celebration", category: "Weddings", eventType: "Wedding", guestCount: "220 guests", location: "Coral Gables", featured: false },
    { id: "g4", url: food.hero, caption: "Seasonal event menu", category: "Food presentation", eventType: "Tasting", guestCount: "Menu detail", location: "Olive & Ember kitchen", featured: false },
    { id: "g5", url: food.dinner, caption: "Corporate lunch spread", category: "Corporate events", eventType: "Corporate lunch", guestCount: "75 guests", location: "Brickell", featured: false },
    { id: "g6", url: food.bread, caption: "A Friday night table", category: "Shabbat", eventType: "Shabbat dinner", guestCount: "28 guests", location: "Aventura", featured: false },
    { id: "g7", url: food.cocktail, caption: "Cocktail hour on the terrace", category: "Weddings", eventType: "Cocktail hour", guestCount: "160 guests", location: "Sunny Isles", featured: false },
    { id: "g8", url: food.pastry, caption: "Morning pastry table", category: "Corporate events", eventType: "Breakfast meeting", guestCount: "40 guests", location: "Downtown Miami", featured: false },
  ],
  leads: [
    { id: "l1", customerName: "Rachel Levin", email: "rachel@example.com", phone: "(305) 555-0182", eventDate: "2026-09-14", eventTime: "18:00", eventLocation: "Vizcaya Museum", eventType: "Wedding", guestCount: 120, budget: "$15,000–$20,000", serviceStyle: "Plated dinner", preferredMenu: "Signature celebration", dietaryRequirements: "Kosher; 4 vegan meals", details: "Outdoor cocktail hour followed by a plated dinner.", preferredContact: "Email", hearAboutUs: "Instagram", receivedAt: "2026-07-24", status: "New", notes: [] },
    { id: "l2", customerName: "Daniel Cohen", email: "daniel@example.com", phone: "(786) 555-0129", eventDate: "2026-08-08", eventTime: "19:30", eventLocation: "Aventura", eventType: "Shabbat dinner", guestCount: 28, budget: "$2,500–$4,000", serviceStyle: "Family style", preferredMenu: "Friday night table", dietaryRequirements: "Nut-free table", details: "Family-style dinner at home.", preferredContact: "WhatsApp", hearAboutUs: "Referral from a friend", receivedAt: "2026-07-20", status: "Contacted", notes: [{ id: "n1", text: "Sent sample Shabbat menu.", createdAt: "2026-07-21" }] },
    { id: "l3", customerName: "Maya Torres", email: "maya@example.com", phone: "(954) 555-0104", eventDate: "2026-10-02", eventTime: "12:30", eventLocation: "Brickell", eventType: "Corporate event", guestCount: 75, budget: "$6,000–$8,000", serviceStyle: "Buffet", preferredMenu: "Mediterranean", dietaryRequirements: "Vegetarian options", details: "Client dinner with passed appetizers.", preferredContact: "Phone", hearAboutUs: "Google search", receivedAt: "2026-07-16", status: "Quote sent", notes: [] },
  ],
  subscription: { plan: "Business", price: 249, status: "Trial" },
  notifications: { emailLeads: true, whatsapp: false, weeklySummary: true },
  onboarded: true,
};
